//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certification
    {
        public int CertId { get; set; }
        public string CertName { get; set; }
        public string CertAuthority { get; set; }
        public string CertLicense { get; set; }
        public string CertDate { get; set; }
        public int JobSeekerJSId { get; set; }
    
        public virtual JobSeeker JobSeeker { get; set; }
    }
}
