//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Recruiters = new HashSet<Recruiter>();
            this.NewsPosts = new HashSet<NewsPost>();
            this.JobPostings = new HashSet<JobPosting>();
        }
    
        public int CompId { get; set; }
        public string CompName { get; set; }
        public string CompCode { get; set; }
        public string CompDescription { get; set; }
        public int NumFollowers { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<Recruiter> Recruiters { get; set; }
        public virtual ICollection<NewsPost> NewsPosts { get; set; }
        public virtual ICollection<JobPosting> JobPostings { get; set; }
        public virtual UserMedia UserMedia { get; set; }
        public virtual Location Location { get; set; }
    }
}
