//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int EduId { get; set; }
        public string CourseName { get; set; }
        public string SchoolName { get; set; }
        public string EduLocation { get; set; }
        public string EduStartDate { get; set; }
        public string EduEndDate { get; set; }
        public string EduDescription { get; set; }
        public string EduGrade { get; set; }
        public int JobSeekerJSId { get; set; }
    
        public virtual JobSeeker JobSeeker { get; set; }
    }
}
