//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Follower
    {
        public int FollowId { get; set; }
        public string ViewNews { get; set; }
        public string ViewJobs { get; set; }
        public string PostSeen { get; set; }
    }
}
