//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApplied
    {
        public int JobAppId { get; set; }
        public string ApplicationDate { get; set; }
        public string AppliedMessage { get; set; }
        public int JobPostingJobPostId { get; set; }
        public int JobSeekerJSId { get; set; }
    
        public virtual JobPosting JobPosting { get; set; }
        public virtual JobSeeker JobSeeker { get; set; }
    }
}
