//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPosting
    {
        public JobPosting()
        {
            this.JobApplieds = new HashSet<JobApplied>();
        }
    
        public int JobPostId { get; set; }
        public string JobTitle { get; set; }
        public string JobType { get; set; }
        public System.DateTime PostStartDate { get; set; }
        public System.DateTime PostEndDate { get; set; }
        public string NumPositions { get; set; }
        public string JobLevel { get; set; }
        public double JobCompensation { get; set; }
        public string Description { get; set; }
        public string JobReq { get; set; }
        public string JobDuties { get; set; }
        public int CompanyCompId { get; set; }
        public int RecruiterRecId { get; set; }
        public string JobVisible { get; set; }
        public string JobCategory { get; set; }
        public string JobSubcategory { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Recruiter Recruiter { get; set; }
        public virtual UserMedia UserMedia { get; set; }
        public virtual ICollection<JobApplied> JobApplieds { get; set; }
        public virtual Location Location { get; set; }
    }
}
