//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSeeker
    {
        public JobSeeker()
        {
            this.Certifications = new HashSet<Certification>();
            this.Educations = new HashSet<Education>();
            this.WorkExperiences = new HashSet<WorkExperience>();
            this.JobApplieds = new HashSet<JobApplied>();
            this.SkillCollections = new HashSet<SkillCollection>();
        }
    
        public int JSId { get; set; }
        public string SkillSummary { get; set; }
        public string PhoneNumber { get; set; }
        public string Visibility { get; set; }
        public string UserName { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual ICollection<Certification> Certifications { get; set; }
        public virtual ICollection<Education> Educations { get; set; }
        public virtual ICollection<WorkExperience> WorkExperiences { get; set; }
        public virtual UserMedia UserMedia { get; set; }
        public virtual ICollection<JobApplied> JobApplieds { get; set; }
        public virtual ICollection<SkillCollection> SkillCollections { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
